name: 6-minute-cron
on:
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          curl --location --request POST 'https://pickle-zeta.vercel.app/api/dai' --header 'Content-Type: application/json' --data-raw '{"address": "${{secrets.ADDRESS}}" }'
