name: 15-minute-cron
on:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --location --request POST 'https://pickle-zeta.vercel.app/api/dai' \
          --header 'Content-Type: application/json' \
          --data-raw '{"address": ${{ secrets.ADDRESS }}}'
