name: 6-minute-cron
on:
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.ADDRESS }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.ADDRESS}} | sed 's/./& /g'
